### PR TITLE
updated column names for DSP-18620

### PR DESCRIPTION
**Pull request by xytxytxyt**
6.8 new api legacy ✅ https://fallout.sjc.dsinternal.org/tests/ui/xian.teng@datastax.com/DGF-StateStreet-DataLoading/1371ed4a-be93-48c6-91b8-3a0e594dbc23/artifacts
6.8 new api native ✅ https://fallout.sjc.dsinternal.org/tests/ui/xian.teng@datastax.com/DGF-StateStreet-DataLoading/6bdd4d3a-fee9-4a91-82d6-a373c11456cc/artifacts
6.8 old api native ❌ but i don't think it's related to this change (see below for error) https://fallout.sjc.dsinternal.org/tests/ui/xian.teng@datastax.com/DGF-StateStreet-DataLoading/48ac45a0-ef66-421b-a614-d83a245d77ff/artifacts
6.8 old api legacy ✅ https://fallout.sjc.dsinternal.org/tests/ui/xian.teng@datastax.com/DGF-StateStreet-DataLoading/d437cf28-7396-4f3e-a72f-157a4db115b7/artifacts

6.7 old api ✅ https://fallout.sjc.dsinternal.org/tests/ui/xian.teng@datastax.com/DGF-StateStreet-DataLoading/13f734b5-e61b-4bcd-a18d-b14e0c182448/artifacts
6.7 new api ✅ https://fallout.sjc.dsinternal.org/tests/ui/xian.teng@datastax.com/DGF-StateStreet-DataLoading/0b7d4df1-dac9-4423-9661-1b7af5830b52/artifacts

this being said... why did DSP-18620 have an effect on this? it was an internal change... shouldn't it have been transparent to the user? and i also noticed that only the new api was affected; the old api was fine

also, can we stop supporting the old api? it's a lot to test whenever we make a change

link to failed load: https://fallout.sjc.dsinternal.org/tests/ui/xian.teng@datastax.com/DGF-StateStreet-DataLoading/48ac45a0-ef66-421b-a614-d83a245d77ff/artifacts/server/node0/load-data_output.txt
i don't know how the underlying code works so i don't know where this is coming from
```
Writing valmonth vals edges
WARN  2019-04-25 06:59:05,983 org.apache.spark.scheduler.TaskSetManager: Lost task 502.0 in stage 8.0 (TID 3613, 10.200.181.226, executor 4): java.lang.NumberFormatException: For input string: "2150784716"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:273)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
	at com.datastax.spark.connector.types.TypeConverter$IntConverter$$anonfun$convertPF$6.applyOrElse(TypeConverter.scala:164)
	at scala.PartialFunction$AndThen.applyOrElse(PartialFunction.scala:189)
	at com.datastax.spark.connector.types.TypeConverter$class.convert(TypeConverter.scala:45)
	at com.datastax.spark.connector.types.TypeConverter$JavaIntConverter$.com$datastax$spark$connector$types$NullableTypeConverter$$super$convert(TypeConverter.scala:170)
	at com.datastax.spark.connector.types.NullableTypeConverter$class.convert(TypeConverter.scala:58)
	at com.datastax.spark.connector.types.TypeConverter$JavaIntConverter$.convert(TypeConverter.scala:170)
	at com.datastax.spark.connector.types.TypeConverter$OptionToNullConverter$$anonfun$convertPF$37.applyOrElse(TypeConverter.scala:861)
	at com.datastax.spark.connector.types.TypeConverter$class.convert(TypeConverter.scala:45)
	at com.datastax.spark.connector.types.TypeConverter$OptionToNullConverter.com$datastax$spark$connector$types$NullableTypeConverter$$super$convert(TypeConverter.scala:844)
	at com.datastax.spark.connector.types.NullableTypeConverter$class.convert(TypeConverter.scala:58)
	at com.datastax.spark.connector.types.TypeConverter$OptionToNullConverter.convert(TypeConverter.scala:844)
	at com.datastax.spark.connector.writer.SqlRowWriter$$anonfun$readColumnValues$1.apply$mcVI$sp(SqlRowWriter.scala:26)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at com.datastax.spark.connector.writer.SqlRowWriter.readColumnValues(SqlRowWriter.scala:24)
	at com.datastax.spark.connector.writer.SqlRowWriter.readColumnValues(SqlRowWriter.scala:12)
	at com.datastax.spark.connector.writer.BoundStatementBuilder.bind(BoundStatementBuilder.scala:99)
	at com.datastax.spark.connector.writer.GroupingBatchBuilder.next(GroupingBatchBuilder.scala:106)
	at com.datastax.spark.connector.writer.GroupingBatchBuilder.next(GroupingBatchBuilder.scala:31)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at com.datastax.spark.connector.writer.GroupingBatchBuilder.foreach(GroupingBatchBuilder.scala:31)
	at com.datastax.spark.connector.writer.TableWriter$$anonfun$writeInternal$1.apply(TableWriter.scala:229)
	at com.datastax.spark.connector.writer.TableWriter$$anonfun$writeInternal$1.apply(TableWriter.scala:197)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:115)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:114)
	at com.datastax.spark.connector.cql.CassandraConnector.closeResourceAfterUse(CassandraConnector.scala:158)
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:114)
	at com.datastax.spark.connector.writer.TableWriter.writeInternal(TableWriter.scala:197)
	at com.datastax.spark.connector.writer.TableWriter.insert(TableWriter.scala:184)
	at com.datastax.spark.connector.writer.TableWriter.write(TableWriter.scala:171)
	at com.datastax.spark.connector.RDDFunctions$$anonfun$saveToCassandra$1.apply(RDDFunctions.scala:36)
	at com.datastax.spark.connector.RDDFunctions$$anonfun$saveToCassandra$1.apply(RDDFunctions.scala:36)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### CODE REVIEW

**Comment by rocco408** [comment]
> why did DSP-18620 have an effect on this? it was an internal change... shouldn't it have been transparent to the user? and i also noticed that only the new api was affected; the old api was fine

The reason why DSP-18620 affected this example, specifically for the new DGF API, is because the new DGF update methods [require the column names in the DF to match that in the underlying DSE-DB table](https://github.com/riptano/bdp/blob/master/dse-graph-server/src/main/scala/com/datastax/bdp/graph/spark/graphframe/dsedb/NativeDseGraphFrame.scala#L303). Side note: these docs need to be updated, I'll do this shortly. This change was introduced in DSP-18404. In this specific example, our edge table looks like this under the hood
```
CREATE TABLE statestreet.valmonth__valmonth_vals__vals (
    valmonth_valmonth_id int,
    vals_vals_id int,
    connect_date text,
    PRIMARY KEY (valmonth_valmonth_id, vals_vals_id)
) WITH CLUSTERING ORDER BY (vals_vals_id ASC)
```
So when constructing the DF in your example, the user must make sure the edge column names match up, along with any properties that are targeted for updating (e.g. connect_date). So the DF looks like this:
```
scala> valmonth_vals_df.select(
     |           col("childitem_id") as getEdgeVertexIdColumnName("valmonth", "out"),
     |           col("vals_id") as getEdgeVertexIdColumnName("vals", "in"),
     |           col("connect_date")
     |         ).show

+--------------------+------------+------------+
|valmonth_valmonth_id|vals_vals_id|connect_date|
+--------------------+------------+------------+
|                   0|           0|  2000-01-01|
|                   0|           1|  2000-01-02|
```
I will update our documentation on this, both scaladoc and best practices, so that we make this crystal clear.

> ...can we stop supporting the old api?

If you're asking whether we should stop supporting the old API in DSE altogether, that may be a question for PM. In my opinion, we should start phasing it out. If you're asking whether we should stop supporting the old API implementation in our tests, I would okay with phases it out after the NGDG release. If I remember correctly, we're not routinely perf testing the old API right now, but I think it's good to have on hand if/when we need to run some more comparative perf tests (e.g. blog posts, marketing, etc.)

**Review by rocco408 — APPROVED** [review]
Thanks, Xian for tackling this. I'm not sure why that one run failed. If it is consistently failing can you open a ticket, please?

**Comment by xytxytxyt** [comment]
okay i'll merge and rerun 6.8 old api native

**Comment by xytxytxyt** [comment]
error is still happening; opened https://datastax.jira.com/browse/DSP-18790

**Pull request merged**
